module.exports = {
  projectName: 'ywt-vue',
  privateKey: 'D:\\Project\\ywt-vue/HENGYU.pem',
  passphrase: '',
  cluster: [],
  dev: {
    name: '开发环境',
    script: 'npm run build:stage',
    host: '192.168.2.10',
    port: 22,
    username: 'root',
    password: '12345678',
    distPath: 'dist',
    webDir: '/app/web/dist',
    bakDir: '',
    isRemoveRemoteFile: true,
    isRemoveLocalFile: false,
  },
  test: {
    name: '测试环境',
    script: 'npm run build:stage',
    host: 'api.jinyiweikeji.com',
    port: 22110,
    username: 'root',
    password: '12345678',
    distPath: 'dist',
    webDir: '/app/web/dist',
    bakDir: '',
    isRemoveRemoteFile: true,
    isRemoveLocalFile: false,
  },
};
